pcap = ENV["PWD"] + "/vagrant.pcap"
script = ENV["PWD"] + "/script.ps1"

Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-10"

  config.vm.define "server" do |server|
    server.vm.network "private_network", ip: "10.0.0.10", virtualbox__intnet: true
    server.vm.provider "virtualbox"
  end

  config.vm.define "client" do |client|
    client.vm.network "private_network", ip: "10.0.0.2", virtualbox__intnet: true

    client.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--nictrace2", "on"]
      vb.customize ["modifyvm", :id, "--nictracefile2", pcap]
    end

    client.vm.synced_folder ENV["PWD"], "/vagrant"

    client.vm.provision "shell", path: script
    client.vm.provision "shell", inline: "New-Item -ItemType file /vagrant/done"
  end
end
